#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path


def render_status(health: dict) -> str:
    special_run = health.get("special_issue_run") or {}
    last_run = health.get("last_run") or {}
    checked_on = health.get("checked_on") or "unknown"
    status = str(health.get("status") or "unknown").title()
    return f"""# Collection Status

Latest public snapshot: **{checked_on}**<br>
Dataset status: **{status}**

| Measure | Value |
|---|---:|
| Public articles | {health.get('article_count', 0)} |
| Latest publication date | {health.get('latest_published_date') or '—'} |
| Active special-issue calls | {health.get('active_special_issue_count', 0)} |
| Upcoming calls | {health.get('upcoming_special_issue_count', 0)} |
| Calls awaiting verification | {health.get('unverified_special_issue_count', 0)} |
| Current priority-journal CFP audits | {health.get('special_issue_audit_coverage_count', 0)}/{health.get('special_issue_priority_journal_count', 0)} |
| Automated CFP sources | {special_run.get('automated_source_count', 0)} |
| Failed CFP sources | {special_run.get('failed_source_count', 0)} |
| Last weekly run | {last_run.get('status') or 'unknown'} |

[Browse the public data](data/public/README.md) · [Open the deployed monitor](https://communication-journal-monitor.ottoto.chatgpt.site/)

This file is generated by the weekly workflow. CFP audit coverage is time-limited; see [`health.json`](data/public/health.json) and the README coverage notes before treating the absence of a call as evidence that none exists.
"""


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: write_public_status.py HEALTH_JSON OUTPUT_MD", file=sys.stderr)
        return 2
    health_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    payload = json.loads(health_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{health_path} must contain a JSON object.")
    output_path.write_text(render_status(payload), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
